version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    ports:
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 8000:32400
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=
      - TZ=Europe/Moscow
      - HOSTNAME=PlexServer
    volumes:
      - /d/home/plex/library:/config
      - /d/home/plex/tvseries:/tv
      - /d/home/plex/movies:/movies
      - /d/home/torrent/downloads:/downloads
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
    volumes:
      - /d/home/torrent/config:/config
      - /d/home/torrent/downloads:/downloads
      - /d/home/torrent/folder:/watch
  bitwarden:
    image: bitwardenrs/server
    container_name: bitwarden
    restart: unless-stopped
    ports:
      - 8003:80
    volumes:
      - /d/home/bitwarden:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
